#!/usr/bin/env node

const TJS = require('typescript-json-schema')
const { resolve } = require('path')
const $RefParser = require('@apidevtools/json-schema-ref-parser')
const ts = require('typescript')

const compilerOptions = {
  strict: true,
  target: ts.ScriptTarget.ES2020,
  module: ts.ModuleKind.CommonJS,
  skipLibCheck: true,
  esModuleInterop: true,
  typeRoots: ['./src', './node_modules/@types']
}

const program = TJS.getProgramFromFiles([resolve(__dirname, 'src/plugin.ts')], compilerOptions)
const schemaFromTs = TJS.generateSchema(program, 'PluginConfig')
let schema = {}
$RefParser.dereference(schemaFromTs, (err, derefSchema) => {
  if (err) {
    console.error(err)
  } else {
    schema = derefSchema
    console.log(JSON.stringify(schema, null, 2))
  }
})
