name: CI Test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & lint
        run: npm install && npm run ci-lint
      - name: Run tests against InfluxDb2
        run: npm run test
